### ISSUE TITLE
SandBox Error

### ISSUE THREAD

**Issue by ayushpateldevvspl** [aexol-studio/react-pdf-editor#84]
Hello please help me,

I am follow the Installation which provide in README.md from Develop Installation. perform all step but after execute npm start command I give me this error :- 

> react-pdf-editor@0.0.0 start
> webpack-dev-server --config ./sandbox/webpack.config.js --content-base ./sandbox/ --port 1568 --hot --inline --open

(node:21827) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
(Use `node --trace-deprecation ...` to show where the warning was created)
ℹ ｢wds｣: Project is running at http://localhost:1568/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /home/vspl/codes/documenso/react_pdf/react-pdf-editor/sandbox
ℹ ｢wds｣: 404s will fallback to /index.html
node:internal/crypto/hash:68
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/home/vspl/codes/documenso/react_pdf/react-pdf-editor/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/vspl/codes/documenso/react_pdf/react-pdf-editor/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/vspl/codes/documenso/react_pdf/react-pdf-editor/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/vspl/codes/documenso/react_pdf/react-pdf-editor/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/vspl/codes/documenso/react_pdf/react-pdf-editor/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/vspl/codes/documenso/react_pdf/react-pdf-editor/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/vspl/codes/documenso/react_pdf/react-pdf-editor/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/home/vspl/codes/documenso/react_pdf/react-pdf-editor/node_modules/loader-runner/lib/LoaderRunner.js:205:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v20.9.0

**Comment by ShubhamSNegi** [comment]
@ayushpateldevvspl Have you found anything on it?

**Comment by ayushpateldevvspl** [comment]
no update?
